config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'home#top'
  
  get 'home/index'
  get 'home/team'
  post 'home/team' => 'home#team'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :common, :only => [:index, :team]
  before_action :authenticate_user!, only: [:index, :team]

  def top
  end
  
  def common
    @hero_name = Faker::Superhero.name
    @hero_power = Faker::Superhero.power
    @corp_power = Faker::Company.bs
    @corp_title = Faker::Name.title
    @corp_power = @corp_power.titleize
    
    @rand_num = rand(1..1000)
    @set_num = rand(1..4)
    @bg = rand(1..2)
    
    #Randomly Pick our avatar set
    if @set_num == 1
      @set = "set1"
    elsif @set_num == 2
      @set = "set2"
    elsif @set_num == 3
     @set = "set3"
    else
      @set = "set4"
    end
    
    #Randomly pick our Background set
    if @bg == 1
      @background = "bg1"
    else
      @background = "bg2"
    end
    
    
    @avatar = Faker::Avatar.image(@rand_num, "300x300", "png", @set, @background)
  end
  
  def index
  end
  
  def team
    @team_number = params[:team_number].to_i
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_create_team.html.erb
<div class="row">
      <br/>
      <div class="col-md-4">
        <%= form_tag home_team_path, :method => 'POST' do %>
        
        <%= select_tag(:team_number, options_for_select([
                      ['1', 1],
                      ['2', 2],
                      ['3', 3],
                      ['4', 4],
                      ['5', 5],
                      ['6', 6],
                      ['7', 7],
                      ['8', 8],
                      ['9', 9],
                      ['10', 10],
        ]), class: "form-control") %>
        
        <br/><br/>
        <%= submit_tag 'Build  Your Team!',class: "btn btn-default" %>
        <% end %>
      </div>
      
      <div class="col-md-4">

      </div>
      
      <div class="col-md-4">
        
      </div>
    </div>

app/views/home/_deviseErrorMsg.html.erb
<% unless resource.errors.empty? %>
 　<script type="text/javascript">
 　　<% resource.errors.full_messages.each do |msg| %>
　　　　　toastr.error('<%= msg %>');
 　　<% end %>
　　</script>
<% end %>
 

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default container-fluid">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SUPERHERO HOME', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        
        <% if user_signed_in? %>
          <li><%= link_to 'SUPERHERO NAME GENERATOR', home_index_path %></li>
            <li><%= link_to 'Create A team', home_team_path %></li>
            
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'ユーザー編集', edit_user_registration_path %></li>
              <li><%= link_to 'サインアウト', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          
          <li><%= link_to 'アカウント作成', new_user_registration_path %></li>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
        <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_show_team.html.erb
<% @team_number.times do %>


    <div class="row">
      <div class="col-md-4"><br/>


    <% rand_num = rand(1..1000) %>
   <% set_num = rand(1..4) %>
    <% bg = rand(1..2) %>
    
    <% if set_num == 1 %>
      <% set = "set1" %>
    <% elsif set_num == 2 %>
      <% set = "set2" %>
    <% elsif set_num == 3 %>
     <% set = "set3" %>
    <% else %>
      <% set = "set4" %>
    <% end %>
    
    <% if bg == 1 %>
      <% background = "bg1" %>
    <% else %>
      <% background = "bg2" %>
    <% end %>
    
    
    <% avatar = Faker::Avatar.image(rand_num, "300x300", "png", set, background) %>




        <img src ="<%= avatar %>"><br/><br/>
      </div>
      
      <div class="col-md-4"><br/>
      <h3>
        Your Superhero Name:<br/>
        <span class="red"><%= Faker::Superhero.name %></span>
      </h3>
      <h3>
        Your Superhero Power: <br/>
        <span class="red"><%= Faker::Superhero.power %></span>
      </h3>
      <br/><br/>
      <h4>
        Your Undrcover Day Job is: <br/>
        <span class="corp_red"><%= Faker::Name.title %></span>
       </h4>
       <h4>
        Your Corporate Superpower is: <br/>
        <span class = "corp_red"><%= Faker::Company.bs %></span>
       </h4>
      </div>
      
      <div class="col-md-4">
        <!--put add code-->
      </div>
    </div>
    <div class="row">
        <div class="col-md-12">
          <hr>  
        </div>
    </div>
    
<% end %>

app/views/home/index.html.erb
<br/>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title gray"><%= link_to 'Click Hero To Generate A New Superhero', home_index_path %></h3>
  </div>
  <div class="panel-body">
    
    
    <div class="row">
      <div class="col-md-4"><br/>
        <img src ="<%= @avatar %>"><br/><br/>
      </div>
      
      <div class="col-md-4"><br/>
      <h3>
        Your Superhero Name:<br/>
        <span class="red"><%= @hero_name %></span>
      </h3>
      <h3>
        Your Superhero Power: <br/>
        <span class="red"><%= @hero_power %></span>
      </h3>
      <br/><br/>
      <h4>
        Your Undrcover Day Job is: <br/>
        <span class="corp_red"><%= @corp_title %></span>
       </h4>
       <h4>
        Your Corporate Superpower is: <br/>
        <span class = "corp_red"><%= @corp_power %></span>
       </h4>
       <br/><br/>
      </div>
      
      <div class="col-md-4">
        <!--put add code-->
      </div>
    </div>

  </div>
  <div class="panel-footer"><%= link_to 'Create A Whole Superhero Team', home_team_path %></div>
</div>

app/views/home/team.html.erb
<br/>





<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title gray"><% if @team_number > 0 %>Your Superhero team...<% else %>How Many Team Menbers Do You What?<% end %></h3>
  </div>
  <div class="panel-body">
    
    
    
    <% if @team_number > 0 %>
      <%= render 'home/show_team' %>
    <% else %>
      <%= render 'home/create_team' %>
    <% end %>
    
    
    
  </div>
  <div class="panel-footer"><%= link_to 'Create A Whole Superhero Team', home_team_path %></div>
</div>

app/views/home/top.html.erb
<br/><br/><br/><br/><br/>
<div class="jumbotron text-center">
  <h1>SUPERHERO HOME PAGE</h1>
  <p>...</p>
  <p><%= link_to 'アカウント作成', new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superhero Name Generator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'home/navbar' %>

<div class="container">
  
  <%= yield %>
  <!-- flashにメッセージがある時 -->
<% unless flash.empty? %>
 　<script type="text/javascript">
 　　<% flash.each do |f| %>
 　　　<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
　　　　　toastr['<%=type %>']('<%=f[1] %>');
 　　<% end %>
　　</script>
<% end %>
 
</div>

<br/><br/>
<br/><br/>
<center>
  Copyright © 2017 JohnElder.org - All Rights Reserved 
</center>
</body>
</html>